# cuda 9.0, gcc 5.4
# cuda 9.2, gcc 7
# cuda 10.0, gcc 7
# cuda 10.1 is not supported, see https://github.com/dmlc/xgboost/issues/4264
# cuda 8.0 and lower are not supported
c_compiler_version:    # [linux]
  - 7.3                  # [linux]
cxx_compiler_version:  # [linux]
  - 7.3                  # [linux]
cudatoolkit:
  - 10.0
python:
  - 3.6
