# GPU variant, builds GPU variants of libxgboost and py-xgboost packages
{% set name = "py-xgboost-gpu" %}
{% set version = "0.82" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # Rename this to dummy since we don't want CB to extract it
  fn: xgboost-{{ version }}-py3-none-any.whl.dummy                                            # [linux]
  url: https://files.pythonhosted.org/packages/6a/49/7e10686647f741bd9c8918b0decdb94135b542fe372ca1100739b8529503/xgboost-0.82-py2.py3-none-manylinux1_x86_64.whl  # [linux]
  sha256: 50619aa6ade391fe0584ff1c9011451cd0c570fcedf94e6d7b3eaa324cb0db31                    # [linux]

build:
  skip: true  # [not linux64 and not win64]
  number: 5

requirements:
  host:
    - python
    - pip
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - git
    - make  # [linux]
  run:
    - python
    - numpy
    - scipy
    - scikit-learn

test:
  requires:
    - pandas
  commands:
    - {{ PYTHON }} ./test-py-xgboost.py
